In [1]:
# import 

import pandas as pd, scipy as sp, numpy as np, seaborn as sb, requests as req, re, wikipedia as wik, urllib as url
from bs4 import BeautifulSoup as beaut

In [28]:
# helper function for quick printing 

def p(string):
    
        """
        Shortens the time to call print.

        Parameters
        ----------
        string: The item to print.

        Returns
        -------
        Prints the string to IO, no return.

        Raises
        ------
        Err when non-convertable.
        """
        
        print(str(string))
        
def pb():
    
        """
        Shortens the time to call print break.

        Parameters
        ----------
        string: The item to print.

        Returns
        -------
        Prints a line break.

        Raises
        ------
        Err when non-convertable.
        """
        
        print('\n')def p(string):
    
        """
        Shortens the time to call print.

        Parameters
        ----------
        string: The item to print.

        Returns
        -------
        Prints the string to IO, no return.

        Raises
        ------
        Err when non-convertable.
        """
        
        print(str(string))

In [29]:
# table_year_vs_numbers

year_vs_numbers = """<table class="wikitable sortable collapsible collapsed" style="text-align:right">
<caption>Terrorist Attacks in the United States<sup class="reference" id="cite_ref-globalterrorismdb_0616dist_3-0"><a href="#cite_note-globalterrorismdb_0616dist-3">[3]</a></sup><sup class="reference" id="cite_ref-gtd1993_0616dist_4-0"><a href="#cite_note-gtd1993_0616dist-4">[4]</a></sup>
</caption>
<tr style="background:#ececec; vertical-align:top;">
<th> Year </th>
<th> Number of<br/>incidents </th>
<th> Deaths </th>
<th> Injuries
</th></tr>
<tr>
<td align="center">2016</td>
<td>61</td>
<td>68</td>
<td>139
</td></tr>
<tr>
<td align="center">2015</td>
<td>38</td>
<td>44</td>
<td>52
</td></tr>
<tr>
<td align="center">2014</td>
<td>26</td>
<td>19</td>
<td>6
</td></tr>
<tr>
<td align="center">2013</td>
<td>19</td>
<td>22</td>
<td>422
</td></tr>
<tr>
<td align="center">2012</td>
<td>18</td>
<td>33</td>
<td>6
</td></tr>
<tr>
<td align="center">2011</td>
<td>10</td>
<td>0</td>
<td>2
</td></tr>
<tr>
<td align="center">2010</td>
<td>17</td>
<td>4</td>
<td>17
</td></tr>
<tr>
<td align="center">2009</td>
<td>10</td>
<td>18</td>
<td>41
</td></tr>
<tr>
<td align="center">2008</td>
<td>18</td>
<td>2</td>
<td>13
</td></tr>
<tr>
<td align="center">2007</td>
<td>9</td>
<td>0</td>
<td>0
</td></tr>
<tr>
<td align="center">2006</td>
<td>6</td>
<td>1</td>
<td>14
</td></tr>
<tr>
<td align="center">2005</td>
<td>20</td>
<td>0</td>
<td>0
</td></tr>
<tr>
<td align="center">2004</td>
<td>9</td>
<td>0</td>
<td>0
</td></tr>
<tr>
<td align="center">2003</td>
<td>32</td>
<td>0</td>
<td>0
</td></tr>
<tr>
<td align="center">2002</td>
<td>33</td>
<td>4</td>
<td>4
</td></tr>
<tr>
<td align="center">2001</td>
<td>41</td>
<td>3,003</td>
<td>6,000+
</td></tr>
<tr>
<td align="center">2000</td>
<td>32</td>
<td>0</td>
<td>7
</td></tr>
<tr>
<td align="center">1999</td>
<td>53</td>
<td>20</td>
<td>40
</td></tr>
<tr>
<td align="center">1998</td>
<td>30</td>
<td>4</td>
<td>3
</td></tr>
<tr>
<td align="center">1997</td>
<td>40</td>
<td>2</td>
<td>18
</td></tr>
<tr>
<td align="center">1996</td>
<td>35</td>
<td>2</td>
<td>119
</td></tr>
<tr>
<td align="center">1995</td>
<td>60</td>
<td>170</td>
<td>734
</td></tr>
<tr>
<td align="center">1994</td>
<td>56</td>
<td>10</td>
<td>16
</td></tr>
<tr>
<td align="center">1993</td>
<td>37</td>
<td>10</td>
<td>1,005
</td></tr>
<tr>
<td align="center">1992</td>
<td>32</td>
<td>2</td>
<td>3
</td></tr>
<tr>
<td align="center">1991</td>
<td>30</td>
<td>2</td>
<td>4
</td></tr>
<tr>
<td align="center">1990</td>
<td>32</td>
<td>5</td>
<td>7
</td></tr>
<tr>
<td align="center">1989</td>
<td>42</td>
<td>3</td>
<td>14
</td></tr>
<tr>
<td align="center">1988</td>
<td>27</td>
<td>1</td>
<td>1
</td></tr>
<tr>
<td align="center">1987</td>
<td>34</td>
<td>1</td>
<td>1
</td></tr>
<tr>
<td align="center">1986</td>
<td>49</td>
<td>1</td>
<td>36
</td></tr>
<tr>
<td align="center">1985</td>
<td>40</td>
<td>3</td>
<td>13
</td></tr>
<tr>
<td align="center">1984</td>
<td>63</td>
<td>3</td>
<td>780
</td></tr>
<tr>
<td align="center">1983</td>
<td>44</td>
<td>8</td>
<td>5
</td></tr>
<tr>
<td align="center">1982</td>
<td>78</td>
<td>11</td>
<td>37
</td></tr>
<tr>
<td align="center">1981</td>
<td>73</td>
<td>8</td>
<td>15
</td></tr>
<tr>
<td align="center">1980</td>
<td>67</td>
<td>15</td>
<td>22
</td></tr>
<tr>
<td align="center">1979</td>
<td>69</td>
<td>18</td>
<td>58
</td></tr>
<tr>
<td align="center">1978</td>
<td>87</td>
<td>8</td>
<td>8
</td></tr>
<tr>
<td align="center">1977</td>
<td>130</td>
<td>4</td>
<td>17
</td></tr>
<tr>
<td align="center">1976</td>
<td>105</td>
<td>4</td>
<td>41
</td></tr>
<tr>
<td align="center">1975</td>
<td>149</td>
<td>24</td>
<td>158
</td></tr>
<tr>
<td align="center">1974</td>
<td>94</td>
<td>16</td>
<td>54
</td></tr>
<tr>
<td align="center">1973</td>
<td>58</td>
<td>45</td>
<td>33
</td></tr>
<tr>
<td align="center">1972</td>
<td>4</td>
<td>10</td>
<td>35
</td></tr>
<tr>
<td align="center">1971</td>
<td>247</td>
<td>20</td>
<td>55
</td></tr>
<tr>
<td align="center">1970</td>
<td>468</td>
<td>33</td>
<td>160
</td></tr>
<tr>
<td align="center">Total</td>
<td>2,728</td>
<td>3,662</td>
<td>10,099+
</td></tr></table>"""

In [30]:
# initialize_page()

#     main = wik.page("Terrorism in the United States")
# #     p(main.title)
# #     p(main.url)
# #     p(main.content)
#     html = wik.WikipediaPage("Terrorism in the United States").html()
#     html = str(html)
    
def initialize_page(page): 
    """
    Loads the page and extracts HTML for future use.

    Parameters
    ----------
    string: The item to print.

    Returns
    -------
    Prints the string to IO, no return.

    Raises
    ------
    Err when non-convertable.
    """ 
    
    global soup
    soup = beaut(page, 'html.parser')

In [31]:
initialize_page(year_vs_numbers)

In [ ]:
years = soup.find_all('td', {'align':'center'}) # years
years_list = []
for year in years:
    p(year)
    years.append(year.content)

In [36]:
year_stats = soup.find_all('td', {'align':None})
counter = 0
stats_table = []
for stat in year_stats:
    p(stat)
    stats_table.append(stat.content)
    
p(stats)

<td>61</td>
<td>68</td>
<td>139
</td>
<td>38</td>
<td>44</td>
<td>52
</td>
<td>26</td>
<td>19</td>
<td>6
</td>
<td>19</td>
<td>22</td>
<td>422
</td>
<td>18</td>
<td>33</td>
<td>6
</td>
<td>10</td>
<td>0</td>
<td>2
</td>
<td>17</td>
<td>4</td>
<td>17
</td>
<td>10</td>
<td>18</td>
<td>41
</td>
<td>18</td>
<td>2</td>
<td>13
</td>
<td>9</td>
<td>0</td>
<td>0
</td>
<td>6</td>
<td>1</td>
<td>14
</td>
<td>20</td>
<td>0</td>
<td>0
</td>
<td>9</td>
<td>0</td>
<td>0
</td>
<td>32</td>
<td>0</td>
<td>0
</td>
<td>33</td>
<td>4</td>
<td>4
</td>
<td>41</td>
<td>3,003</td>
<td>6,000+
</td>
<td>32</td>
<td>0</td>
<td>7
</td>
<td>53</td>
<td>20</td>
<td>40
</td>
<td>30</td>
<td>4</td>
<td>3
</td>
<td>40</td>
<td>2</td>
<td>18
</td>
<td>35</td>
<td>2</td>
<td>119
</td>
<td>60</td>
<td>170</td>
<td>734
</td>
<td>56</td>
<td>10</td>
<td>16
</td>
<td>37</td>
<td>10</td>
<td>1,005
</td>
<td>32</td>
<td>2</td>
<td>3
</td>
<td>30</td>
<td>2</td>
<td>4
</td>
<td>32</td>
<td>5</td>
<td>7
</td>
<td>42</td>
<td>3</td>
<td>14
</td>
<td>27</td>
<td>1</td>
<td>1
</td>
<td>34</td>
<td>1</td>
<td>1
</td>
<td>49</td>
<td>1</td>
<td>36
</td>
<td>40</td>
<td>3</td>
<td>13
</td>
<td>63</td>
<td>3</td>
<td>780
</td>
<td>44</td>
<td>8</td>
<td>5
</td>
<td>78</td>
<td>11</td>
<td>37
</td>
<td>73</td>
<td>8</td>
<td>15
</td>
<td>67</td>
<td>15</td>
<td>22
</td>
<td>69</td>
<td>18</td>
<td>58
</td>
<td>87</td>
<td>8</td>
<td>8
</td>
<td>130</td>
<td>4</td>
<td>17
</td>
<td>105</td>
<td>4</td>
<td>41
</td>
<td>149</td>
<td>24</td>
<td>158
</td>
<td>94</td>
<td>16</td>
<td>54
</td>
<td>58</td>
<td>45</td>
<td>33
</td>
<td>4</td>
<td>10</td>
<td>35
</td>
<td>247</td>
<td>20</td>
<td>55
</td>
<td>468</td>
<td>33</td>
<td>160
</td>
<td>2,728</td>
<td>3,662</td>
<td>10,099+
</td>